FROM fedora:latest

RUN dnf install -y git cmake gcc-c++ qt5-qtbase-devel \
qt5-qtquickcontrols2-devel gdb valgrind omniORB-devel \
omniORB-servers patch protobuf-devel freeglut-devel npm \
libpng12 libpng-devel SDL2* qt qt-creator qt-devel \
qt5-qtserialport* qt5-qtconnectivity* qt5-qtmultimedia \
eigen3-devel protobuf-devel libdc1394* libjpeg-turbo \
gtkmm24-devel omniORB* redhat-rpm-config opencv-devel \
golang nodejs

SHELL ["/bin/bash", "-c"]
